### ISSUE TITLE
If process exits too quickly an exeption is thrown on 3.2.1 (but not on 3.2.0)

### ISSUE THREAD

**Issue by Mgamerz** [Tyrrrz/CliWrap#95] opened 2020-11-04 04:45 UTC
I have an executable I'm running on Linux (https://github.com/MassEffectModder/MassEffectModder/releases/tag/427 MassEffectModderNoGui-Linux-v427.zip) and after updating to 3.2.2 from 3.1.0 I now get unhandled exceptions when calling the executable. This call exits _very_ quickly - it just prints the version info for me to read. `time` shows 0.07 seconds.

The exception is shown here as 'Cannot process request because the process has exited'.

![image](https://user-images.githubusercontent.com/2738836/98070028-8dfd3a80-1e1d-11eb-8c90-0652e4d4886a.png)

I tested on 3.1.0 and 3.2.0 and 3.2.1. I don't get this error on those. I get it once I change to 3.2.2 and it is a consistent error.

I invoke this program in this fashion: `/home/mgamerz/.local/share/ALOTInstallerConsole/MassEffectModderNoGui --version --ipc` if you want to test it out. 

I'll probably switch back to 3.1.0 because I'm on a real tight deadline but I thought I'd post this here so you could take a look at it. There's a Windows version of this executable, however it doesn't have this problem, I assume because it's a bit slower.

**Comment by Tyrrrz** [comment] 2020-11-04 14:15
Thanks for reporting.
This is a duplicate of #93.
I've pushed a new version with a fix now (3.2.3).

**Closed by Tyrrrz** 2020-11-04 14:15 UTC

**Comment by Mgamerz** [comment] 2020-11-07 02:23
My app comes out tomorrow, so I'll be able to update the library and test again after that. Thanks for the quick fix.
