### ISSUE TITLE
Trouble running within Windows Service

### ISSUE THREAD

**Issue by ajweber** [Tyrrrz/CliWrap#52] opened 2020-03-25 23:36 UTC
I have been testing a Windows Service that uses CliWrap and on my DEV machine it works fine.

However, when I try copying the binaries (including all the assemblies that VS2019 included in the output), I get this stack trace:
`System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.String> System.Diagnostics.ProcessStartInfo.get_Environment()'.
   at CliWrap.Command.GetStartInfo()
   at CliWrap.Command.ExecuteAsync(CancellationToken cancellationToken)`

Can you help me figure out what dependency CliWrap is looking for?  I can't find anything missing as far as I've looked!

FWIW: Building/Targeting .Net 4.6.1

Thanks.

**Comment by Tyrrrz** [comment] 2020-03-26 10:27
Hi.

Not sure what could cause this. Try creating a distribution via `dotnet publish -o output_dir/` if you weren't doing that already.

**Comment by ajweber** [comment] 2020-03-26 12:35
Interesting, dotnet publish warns me that there are "support references to libraries targeting .NET Standard 1.5 or higher."

How is it I'm able to build targeting .Net 4.6.1, but some assemblies must be targeting .Net Standard???  Is it allowed that dependencies can have higher .Net dependencies than the main exe's targeted .Net version?

**Comment by Tyrrrz** [comment] 2020-03-26 12:55
It seems that .net461 is compatible with .netstd1.5 but with some caveats:

![image](https://user-images.githubusercontent.com/1935960/77649057-d2fcec80-6f71-11ea-8c77-bdf2dcf0ab21.png)

**Comment by Tyrrrz** [comment] 2020-03-26 12:58
Not sure if upgrade is viable for you, but can you try to see if the problem is reproducible if you target net472? Or maybe try removing the dependency you're using which targets .netstd1.5 and see what happens, just to isolate the issue.

**Comment by ajweber** [comment] 2020-03-26 15:15
Re-targeting to .Net 4.7.2 resolved the issue.  Very interesting find by you.  Thank you.

**Comment by Tyrrrz** [comment] 2020-03-26 15:43
Cool :)
I'll close this as it's not in fact related to CliWrap, it doesn't have any .NET Standard 1.5 dependencies.

**Closed by Tyrrrz** 2020-03-26 15:43 UTC
Labels: invalid

**Comment by ajweber** [comment] 2020-03-26 16:31
I thank you for your help, but just for reference, the NuGet download I have shows this:
`[Reflection.Assembly]::LoadFile('...\bin\Debug\CliWrap.dll').GetReferencedAssemblies()

Version        Name
-------        ----
4.0.0.0        mscorlib
4.0.0.0        System.Management
4.0.0.0        System
4.2.0.1        System.Threading.Tasks.Extensions
4.0.2.0        System.ValueTuple
1.0.0.0        Microsoft.Bcl.AsyncInterfaces
4.0.0.0        System.Core
2.0.0.0        netstandard`

**Comment by Tyrrrz** [comment] 2020-03-26 18:20
Yeah for .NET Framework it has some extra dependencies to polyfill the missing APIs, but they should all multitarget for .NET461 so I don't think that's the issue.

**Comment by ajweber** [comment] 2020-03-26 18:39
I'm still not sure.  The exe/service ran until it tried to 
ExecuteAsync() the CliWrap command, then it dumped the stack trace that 
appears to indicate that the ProcessInfo method is not correct.

The best course of action is to use 4.7.2 when targeting old-school .Net 
Framework, but I hesitate to agree that this dependency was caused by a 
different one of my program's references.

Thanks again for your help.
