### ISSUE TITLE
Able to start process with Shell.

### ISSUE THREAD

**Issue by Wyvernius** [Tyrrrz/CliWrap#186] opened 2023-01-03 16:54 UTC
### Details

Currently there is no way of defining if the process is started from shell.
Could this be added or is it left out on purpose?

**Comment by Tyrrrz** [comment] 2023-01-05 04:54
It's left out on purpose. With shell execute, we can't access process streams.

Duplicate of #114

**Closed by Tyrrrz** 2023-01-05 04:54 UTC
Labels: duplicate
