### ISSUE TITLE
Windows 11 throws exception for some arguments passed to SqlPackage

### ISSUE THREAD

**Issue by argentini** [Tyrrrz/CliWrap#205] opened 2023-04-28 22:58 UTC
### Version

Latest

### Details

Using CliWrap to execute Microsoft SqlPackage in a .NET 7 console application for this project: [https://github.com/argentini/Argentini.SqlPkg](https://github.com/argentini/Argentini.SqlPkg). Working great on macOS but on Windows 11 (x64) I get an exception depending on the arguments used.

It seems to work with most arguments but specifically passing no arguments, or passing the help argument, seem to trigger the exception. Getting the version using that argument works, as do all others. This is very odd. When these are run in PowerShell it all works fine.

One more note: This occurs when installing and using the SqlPackage via the dotnet tool install. If I put the fully qualified path to an instance of SqlPackage.exe already on my drive in the Visual Studio path, that one works fine.

![code](https://user-images.githubusercontent.com/1504331/235266632-1a58c6df-ba77-4462-8fd2-316a0ae76424.png)

![exception](https://user-images.githubusercontent.com/1504331/235266643-94377a67-a69c-4e24-b36f-55edb35b8456.png)

The following alternative code works:

```
Process p;
p = new Process();
p.StartInfo.UseShellExecute = false;
p.StartInfo.FileName = "sqlpackage.exe";
p.Start();
p.WaitForExit();
```

### Steps to reproduce

Install SqlPackage as below then try calling it from CliWrap with no arguments using a Windows 11 x64 machine.

```
dotnet tool install -g microsoft.sqlpackage
```

**Comment by Tyrrrz** [comment] 2023-04-29 18:01
Does that program consume stdin for anything? I think this happens because CliWrap always redirects all standard streams, and some programs may infer that if stdin is redirected, then the user intends to write something to it.

I'm not familiar with `SqlPackage` but maybe there's an argument you can pass to explicitly disable that behavior. Otherwise, you can try passing `PipeSource.FromStream(Stream.Null)` for the standard input pipe, but it will probably just result in a different error.

Also see #190, which might be a similar issue.

**Comment by argentini** [comment] 2023-04-29 18:40
Hey @Tyrrrz thanks for the quick response! I did try handling the standard input in that way but I got the same result. I don't believe that SqlPackage bothers with standard input anyway; none of the docs indicate that you can pipe to it.

Attached here is a simple project that shows the failure. Just use the dotnet command below to install SqlPackage, and then run this project.

```
dotnet tool install -g microsoft.sqlpackage
```

[ConsoleApp1.zip](https://github.com/Tyrrrz/CliWrap/files/11359871/ConsoleApp1.zip)

**Comment by Tyrrrz** [comment] 2023-04-30 14:26
I was able to reproduce the error with the following minimal code:

```csharp
using var process = new Process
{
    StartInfo = new ProcessStartInfo
    {
        FileName = "sqlpackage",
        RedirectStandardOutput = true,
        RedirectStandardError = true
    }
};

process.OutputDataReceived += (sender, args) =>
{
    if (args.Data is not null)
    {
        Console.WriteLine(args.Data);
    }
};

process.ErrorDataReceived += (sender, args) =>
{
    if (args.Data is not null)
    {
        Console.WriteLine(args.Data);
    }
};

process.Start();
process.BeginOutputReadLine();
process.BeginErrorReadLine();

process.WaitForExit();
```

Note that the error appears to only happen when both the output and error streams are redirected, but not when only one of them is.

All in all, this looks like either a bug within the `Process` class or inside the implementation of `SqlPackage` (which is more likely). I would recommend raising an issue with them, using the code snippet above. Since this issue is not specific to CliWrap (seeing as it's reproducible with raw `Process`), I'm going to close it.

**Closed by Tyrrrz** 2023-04-30 14:26 UTC
Labels: invalid

**Comment by argentini** [comment] 2023-04-30 20:22
Hey @Tyrrrz thanks for digging into this. I did place an issue with Microsoft about this, so we'll see wha they say.

I noticed that you're sample code isn't following Microsoft's recommendations when redirecting outputs. In my workaround code I am redirecting both and have no issues using Process() with code like this.

```c#
var p = new Process();

p.StartInfo.UseShellExecute = false;
p.StartInfo.FileName = "sqlpackage.exe";
p.StartInfo.RedirectStandardOutput = true;
p.StartInfo.RedirectStandardError = true;
p.ErrorDataReceived += (_, e) => { _ += e.Data; };
p.Start();
p.BeginErrorReadLine();

_ = await p.StandardOutput.ReadToEndAsync();  			    

await p.WaitForExitAsync();
```

Some of Microsoft's comments include:

1. You must set UseShellExecute to false if you want to set RedirectStandardOutput/RedirectStandardError to true. Otherwise, reading from the StandardError stream throws an exception.
2. Microsoft also recommends performing that ReadToEndAsync() prior to WaitForExit(), which also avoids a deadlock or some other exception condition.

Can you modify your test code accordingly and see if it works for you as well?

**Comment by Tyrrrz** [comment] 2023-06-06 18:28
Great! @argentini
