### ISSUE TITLE
Send command after execution

### ISSUE THREAD

**Issue by Piedone** [Tyrrrz/CliWrap#59] opened 2020-04-24 22:37 UTC
Let's suppose I have a long-running command-line app that exits on Ctrl+C. How would I model this with CliWrap? Startup is simple but once it runs how can I send it a Ctrl+C command? Would writing a line to a stream piped onto stdin work even after `ExecuteAsync()`?

Thank you.

**Comment by Tyrrrz** [comment] 2020-04-25 13:09
You currently can't send a SIGINT. The cancellation token kills the process directly.
Duplicate of #47

**Closed by Tyrrrz** 2020-04-25 13:09 UTC
Labels: duplicate

**Comment by Piedone** [comment] 2020-04-25 13:15
OK, so Ctrl+C is not needed, but still, how can I send a command after execution?

**Comment by Tyrrrz** [comment] 2020-04-25 13:23
Hmm. What do you mean by sending a command after execution exactly? If you want to send another command you just do it sequentially:

```csharp
await Cli.Wrap("foo").WithArguments("bar").ExecuteAsync();
await Cli.Wrap("foo").WithArguments("baz").ExecuteAsync();
```

**Comment by Piedone** [comment] 2020-04-25 14:33
I mean sending a command to an already running process. I.e.:

```
using var cancellationTokenSource = new CancellationTokenSource();
using var stream = new MemoryStream();
Cli
    .Wrap("LongRunning.exe")
    .WithStandardInputPipe(PipeSource.FromStream(stream))
    .ListenAsync(cancellationTokenSource.Token);

using var writer = new StreamWriter(stream);
await writer.WriteAsync("command 1");
await writer.WriteAsync("command 2");
```

So basically an interactive console app.

I actually tried the above but couldn't really get it working.

**Comment by Tyrrrz** [comment] 2020-04-25 14:44
Try writing before running the CLI?

**Comment by Piedone** [comment] 2020-04-25 14:52
But that's not what I need. I need to send commands while the app is running, based on what it does. I can't provide the commands in advance, nor can those be passed as startup arguments. So really, imagine any interactive console app.

**Comment by Tyrrrz** [comment] 2020-04-25 15:01
When the application decides to read stdin can't be easily determined.

For example, the app may have:

```csharp
var a = Console.ReadLine();
// ...
var b = Console.ReadLine();
```

Which would mean that it reads the first line of the stream, then does something, then reads the second line. It doesn't matter when those lines were written in the first place.

If you want to write something to stdin *based on the output in stdout/stderr* then this is not supported currently because the stdin stream is closed before stdout/stderr are read.

This could probably be implemented, but supporting interactive console applications isn't the goal of this library -- it's designed to work with CLIs.

**Comment by Piedone** [comment] 2020-04-25 15:29
Got it, thanks.
