### ISSUE TITLE
PipeTarget.Merge can malform the data when using variable-length encoding (like UTF-8)

### ISSUE THREAD

**Issue by tompazourek** [Tyrrrz/CliWrap#81] opened 2020-09-05 10:36 UTC
Hi @Tyrrrz,

I think there's a strange issue in the `PipeTarget.Merge` code that copies the buffers around to streams, I am just not able to really pinpoint it.

The copying of the buffers in `MergedPipeTarget` works on byte-level, but when we read the characters (or lines) from it in other targets, we often work on char-level (in any of the PipeTargets that use a `StreamReader`). And my theory is that when it copies the buffer, it can actually copy a part of a character that the reader can struggle with.

I'll try to show my thoughts on an example. Let's say that a program produces a string of 10,000 hearts (❤). In UTF-8, this will be encoded as 30,000 bytes, it will look like bytes 226, 157, 164 repeated ten thousand times (assuming we don't output BOM in the beginning). Characters in UTF-8 have sometimes 1 byte, sometimes 2 bytes, sometimes 3 bytes, and sometimes 4 bytes. That heart has 3 bytes.

Then we copy a buffer with the size of e.g. 4096 bytes into a stream to the PipeTarget that is merged. If we fill the buffer, it will contain 1365 hearts, and then the byte value 226 (a third of the heart character in UTF-8).

Then a reader tries to read characters from such buffer, but it doesn't recognize the last value 226 as a UTF-8 character, so it can either skip it or misread it somehow. I think that this will happen every time that the length of copied the buffer doesn't align with the UTF-8 characters inside of it.

I tried to provide some repro case in https://github.com/tompazourek/CliWrap/tree/merge-bug-repro, but I had to make the stream buffer size smaller to actually show it. It's not that great of an example, but the best I could come up with at the moment. It does show that when you use the merge target, it breaks it, and when you don't use the merging, it works.

I think the issue might be buried somewhere in `HalfDuplexStream`, but I didn't understand that code well enough to pinpoint it.

**Comment by Tyrrrz** [comment] 2020-09-05 11:22
Hi @tompazourek 

This is indeed an issue. Like you said, the merger is handing the data at a byte level, not character level.

However, I don't think the issue is in `HalfDuplexStream`. You can think of it as "just" a `MemoryStream` that lets you write and read data separately (writing doesn't offset position), and it doesn't complete until explicitly told to (via `ReportCompletionAsync`).

The workflow involving half-duplex streams is actually pretty simple:

1. Create a half-duplex stream for each underlying pipe target
2. Start copying bytes from those half-duplex streams to each of the underlying pipe target's streams (at this point the half-duplex streams are still empty so nothing happens)
3. Start copying bytes from master stream to each of the half-duplex streams in chunks of 81920 bytes (this fills up the half-duplex streams and activates the operations from previous stage)
4. After the master stream reached EOF, send completion signal to half-duplex streams, informing that there will be no more bytes transmitted
5. Wait until all copy operations have finished
6. Clean up resources used by half-duplex streams

Now, as far as character corruption is concerned, it happens simply because the buffer is limited in size. If the process writes more characters in bytes that it can handle at one time, it's possible that one character per buffer will be read incorrectly. Given the buffer's size of 81920 bytes, you will need about 27307 hearts written _at one time_ (as part of a single `Console.Write()`) to cause the overflow. Hence why it happens very rarely.

I have no idea why the non-merged pipe target doesn't exhibit this error however. Can you try setting the `BufferSizes.StreamReader` to the same value to see what happens? Logically, it should work exactly the same, so it's surprising.

If it does also exhibit the same problem, a possible solution would be to avoid reading the last X characters unless they are followed by EOF. Where X is the longest sequence of code points that may make up a single character in the specified encoding.

**Comment by tompazourek** [comment] 2020-09-05 11:41
@Tyrrrz The `BufferSizes.StreamReader` is actually size of the `char` buffer, where each `char` is 2 bytes in .NET, so it's not exactly the same.  And I think it only affects the size of the target char buffer, there might be another intermediate byte buffer in the inner implementation of `StreamReader.ReadAsync` somewhere. But it's a good point that you make -- finding out why it's different between the merged and non-merged could be a good starting point to see if there's something that can be done about this.

Regarding the size of the buffers, it happens regardless of the size if it's not divisible by 3 in my example (because I use strictly a sequence of 3 byte characters). And I couldn't find a way to break it when not using merging yet.

You say you'd need 27307 hearts written at one time to cause the overflow, but it can happen normally if you use 81919 bytes of ASCII characters, and then a single heart, or a different unicode character, and it breaks. If there's a program that has an output buffer larger than 81920 bytes, and it outputs a lot of UTF-8 characters, I think it's still quite likely it can happen. In most cases, we're lucky that CliWrap's buffer is larger than most programs' output buffers, but that might not be always the case.

**Comment by Tyrrrz** [comment] 2020-09-05 12:55
> ...is actually size of the char buffer, where each char is 2 bytes in .NET, so it's not exactly the same

Ah, right. Forgot about that.

> You say you'd need 27307 hearts written at one time to cause the overflow, but it can happen normally if you use 81919 bytes of ASCII characters, and then a single heart, or a different unicode character, and it breaks. 

Yes, I meant to highlight that that's quite a lot of characters to write as a single operation regardless. It was just to explain why it's rare.

Anyway, I'm really curious if `StreamReader` is doing anything special itself. If it does, maybe we make use of that. Otherwise, we'd have to implement more intelligent character reading in some targets.

**Comment by tompazourek** [comment] 2020-09-05 18:50
Yeh, it's an interesting issue. I'm curious myself about what really is the culprit. I don't believe that this is an issue everywhere where one uses the regular streams and readers, so there has to be a reason.

I hope I find some time and maybe figure it out.

**Comment by Tyrrrz** [comment] 2020-09-05 19:14
Ha, I might've had an epiphany on what could be the issue. It's possible the problem is in `HalfDuplexStream` after all.

The way it works is that once there is any amount of data written to it, it becomes available to read for the consumer. That means that if the consumer asks for e.g. 4096 bytes but only 100 were written, then it fills the buffer with only 100 bytes. On the other hand, a normal stream probably doesn't yield until either it can fill the buffer completely, or the stream has ended.

**Comment by tompazourek** [comment] 2020-09-05 19:34
I think I figured it out as well.

Here you pass the `buffer` into the `WriteAsync` method of `HalfDuplexStream`:

https://github.com/Tyrrrz/CliWrap/blob/26ad3f5d1550fe51304733a625644ce4cb3c456f/CliWrap/PipeTarget.cs#L214

But it's passed as reference, and that reference is later modified outside of the semaphore locks. It should be copied instead.

**Comment by Tyrrrz** [comment] 2020-09-05 19:39
Hmm. Can you try it and see if it works?

**Comment by tompazourek** [comment] 2020-09-05 19:45
If I modify this code:

https://github.com/Tyrrrz/CliWrap/blob/26ad3f5d1550fe51304733a625644ce4cb3c456f/CliWrap/Internal/Extensions/CollectionExtensions.cs#L7-L15

as follows (adding `.ToArray()` to these `arr` expressions):

```csharp
        public static T[] Offset<T>(this T[] arr, int count) =>
            count > 0
                ? arr.Skip(count).ToArray()
                : arr.ToArray();

        public static T[] Trim<T>(this T[] arr, int count) =>
            arr.Length > count
                ? arr.Take(count).ToArray()
                : arr.ToArray();
```

Then the issue disappears. :smile:

It's probably not the ideal solution, but it seems to work... Maybe all of this buffer manipulation could be written without LINQ?

**Comment by Tyrrrz** [comment] 2020-09-05 22:10
Nice! So I guess both my theories were incorrect in the end. Still not completely sure why does the original implementation cause an issue in these very specific circumstances, but at least you found a way to fix it.

Can you make a PR for this and also include the test that fails in the original implementation? Ideally, if it can replicate the issue without changing the buffer size constant.

**Comment by tompazourek** [comment] 2020-09-06 07:10
Yeh, all my theories were wrong as well. It actually has nothing to do with UTF-8 and encoding. I've seen mangled Unicode characters as the symptom, so all my thinking revolved around thinking it's to do with Unicode.

Basically the bug will happen every time there's a `PipeTarget.Merge` used and the command's output buffer is larger than that of CliWrap (81,920 bytes). I was able to reproduce it with the hearts because I lowered the buffer size. I thought the data was mangled only sometimes on the edge of the buffer, but in reality, it was the whole content of the buffer that is wrong. I just didn't notice that in my test case because it was all hearts... :smile: And if the buffer had the right size (multiple of 3), I didn't notice that the buffer contents were different, because it would actually end up having the same contents before and after. Hope that explains it.

Well anyway, I'm glad that the Unicode stuff is actually alright in these streams and readers, and it was just a silly buffer reference thing.

**Comment by Tyrrrz** [comment] 2020-09-06 10:22
> Hope that explains it.

Can't say I fully understood it, but it's okay :)

> I still think that the buffer manipulation would be better without all that LINQ (maybe using the Span type). But I'm not yet very familiar with that stuff, so I didn't want to get into it. It could be an interesting refactor for the future, it could bring some performance, as it could avoid allocating enumerators every time a new buffer data arrives.

Absolutely. Performance-wise, there are various areas that could be improved.

**Closed** 2020-09-06 10:26 UTC
Labels: bug
